name: Deploy Cloud Function
on:
  push:
    branches: [ main ]

jobs:
  run:
    # worker runs on latest ubuntu
    runs-on: ubuntu-latest

    steps:
      # checkout to our repository so we have access to the source code
      - uses: actions/checkout@v2

      # the actual deployment to google
      - name: Cloud Functions Deploy
        uses: google-github-actions/deploy-cloud-functions@v0.1.2
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          name: ticket-cart-checker
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          source_dir: ticket-cart-checker
          # name of our function in our main.py file, defaults to the resource name suffix
          entry_point: main
          # runtime to use for the function
          runtime: nodejs16
          # the function execution timeout
          timeout: 60
          # the maximum number of instances for the function.
          max_instances: 3
