name: Deploy Cloud Function
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{secrets.GCP_PROJECT_ID}}
          service_account_key: ${{secrets.GCP_SA_KEY}}
          export_default_credentials: true

      - name: 'deploy'
        id: deploy
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: ticket-cart-checker
          runtime: 'nodejs16'
          project_id: ${{secrets.GCP_PROJECT_ID}}
          entry_point: functions.main
          source_dir: /ticket-cart-checker

      - name: test the url
        run: curl "${{ steps.deploy.outputs.url }}"
