name: Deploy ticket-cart-checker Cloud Function
on:
  push:
    branches: [ main ]

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: 'ticket-cart-checker'
          runtime: 'nodejs16'
          source_dir: ticket-cart-checker
          entry_point: main
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          env_vars: MONGODB_URI=mongodb+srv://admin:admin@cloud-ticket.874mo1m.mongodb.net/?retryWrites=true&w=majority

      # Example of using the output
      - id: 'test'
        run: 'curl "${{ steps.deploy.outputs.url }}"'



